[package]
name = "ctp-common"
version = "0.4.0"
authors = ["Wangshan Lu <wisagan@gmail.com>"]
build = "build.rs"

[dependencies]
encoding = "0.2"
memchr = "0.1"
simple-error = "0.1"
time = "0.1"

[build-dependencies]
bindgen = "0.16"
encoding = "0.2"
xmltree = "0.4"
