sudo: false
language: rust
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
    packages:
      - libclang-3.6-dev
      - llvm-3.6-dev

# run builds for all the trains (and more)
rust:
  - nightly

# the main build
script:
  - cargo build --verbose --manifest-path ctp-common/Cargo.toml
  - cargo test --verbose --manifest-path ctp-common/Cargo.toml
  - cargo build --verbose --manifest-path ctp-md/Cargo.toml
  - cargo build --verbose --manifest-path ctp-trader/Cargo.toml
