[package]
name = "ctp-md"
version = "0.7.0"
authors = ["Wangshan Lu <wisagan@gmail.com>"]
links = "ctp-md"

[features]
channel = ["crossbeam-channel"]

[dependencies]
crossbeam-channel = { version = "0.2.4", optional = true }

[dependencies.ctp-common]
version = "0.7.0"
path = "../ctp-common"
