[package]
name = "ctp-trader"
version = "0.6.0"
authors = ["Wangshan Lu <wisagan@gmail.com>"]
links = "ctp-trader"

[features]
channel = ["crossbeam-channel"]

[dependencies]
crossbeam-channel = { version = "0.2.4", optional = true }

[dependencies.ctp-common]
version = "0.6.0"
path = "../ctp-common"
